TRUNCATE TABLE module;
insert into module (ects, name) VALUES (6,'Einführung in die Informatik / Digitaltechnik');
insert into module (ects, name) VALUES (5,'Lineare Algebra');
insert into module (ects, name) VALUES (5,'Wissenschaftliches Arbeiten / Labor');
insert into module (ects, name) VALUES (5,'Einführung in die Programmierung');
insert into module (ects, name) VALUES (6,'Elektrotechnik / Elektronik');
insert into module (ects, name) VALUES (5,'Vertiefung Programmierung');
insert into module (ects, name) VALUES (5,'Projektarbeit I');
insert into module (ects, name) VALUES (5,'Alogrithmen und Datenstrukturen / Automaten und Sprachen');
insert into module (ects, name) VALUES (5,'Analysis');
insert into module (ects, name) VALUES (10,'Betriebssysteme und Rechnernetze');
insert into module (ects, name) VALUES (5,'Objektorientierte Programmierung');
insert into module (ects, name) VALUES (5,'Projektarbeit II');
insert into module (ects, name) VALUES (9,'Datenbanken');
insert into module (ects, name) VALUES (5,'Statistik / Optimierung');
insert into module (ects, name) VALUES (7,'Systementwicklung');
insert into module (ects, name) VALUES (3,'IT-Trends');
insert into module (ects, name) VALUES (5,'Projektarbeit III');
insert into module (ects, name) VALUES (6,'ABWL und spezielle Managementfelder');
insert into module (ects, name) VALUES (3,'Englisch');
insert into module (ects, name) VALUES (4,'Spezielle Themen I');
insert into module (ects, name) VALUES (5,'Technische Informatik');
insert into module (ects, name) VALUES (5,'MPP I');
insert into module (ects, name) VALUES (7,'Systemprogrammierung, Verteilte Systeme und Netzwerkadministration');
insert into module (ects, name) VALUES (4,'Spezielle Themen II');
insert into module (ects, name) VALUES (6,'E-Commerce und Webbasierte Anwendungen');
insert into module (ects, name) VALUES (5,'Graphische Datenverarbeitung');
insert into module (ects, name) VALUES (5,'Projektarbeit IV');
insert into module (ects, name) VALUES (8,'IT-Management');
insert into module (ects, name) VALUES (4,'Spezielle Themen III');
insert into module (ects, name) VALUES (5,'Maschinelles Lernen / Computerforensik');
insert into module (ects, name) VALUES (5,'MPP II');
insert into module (ects, name) VALUES (12,'Bachelorarbeit');
