name: Release

on:
  workflow_dispatch:

jobs:
  Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew clean build -x test

            - name: Release Jar file
              run: mv build/libs/$(ls build/libs) app.jar
            - uses: actions/upload-artifact@master
              with:
                name: BachelorGrade
                path: app.jar
