name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test & Build"]
    types:
      - completed

jobs:
  Jar:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
              java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Release Jar file
        run: mv build/libs/$(ls build/libs) app.jar
      - uses: actions/upload-artifact@master
        with:
            name: BachelorGrade
            path: app.jar

  Docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker Container & Push to Registry
      run: |
       docker build . --file Dockerfile --tag ghcr.io/johannesf99/bachelor_grade:latest
       docker push ghcr.io/johannesf99/bachelor_grade:latest

  
