name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test & Build"]
    types:
      - completed

jobs:
  Build:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
              java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Release Jar file
        run: mv build/libs/$(ls build/libs) app.jar
      - uses: actions/upload-artifact@master
        with:
            name: BachelorGrade
            path: app.jar

  DockerbuildAndPush:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t bachelor_grade

      - name: Archive Docker image
        uses: actions/upload-artifact@v2
        with:
          name: bachelor_grade
          path: /var/
  
